config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'parties#index'

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/auth/spotify', as: :spotify_oauth
  get '/auth/spotify/callback', to: 'sessions#create', as: :spotify_callback
  get '/soundcheck', to: 'host/parties#edit', as: :soundcheck
  get '/admissions', to: 'parties#new', as: :admissions
  post '/admissions', to: 'parties#create', as: :join_party
  get '/party', to: 'parties#show', as: :party
  delete '/party', to: 'parties#delete', as: :leave_party
  get '/legal', to: 'legal#show', as: :legal
  get '/host', to: 'host/parties#show', as: :host_party
  put '/host', to: 'host/parties#update', as: :update_host_party
  delete '/host/party', to: 'host/parties#destroy', as: :cancel_party

  namespace :api do
    namespace :v1 do
      scope :me, module: :me do
        get '/available_devices', to: 'devices#index', as: :available_devices
        get '/track_status',to: 'track_status#show', as: :track_status
        get '/save_track', to: 'track_status#create', as: :save_track
        get '/currently_playing', to: 'tracks#show', as: :currently_playing
        put '/start_playback', to: 'tracks#update', as: :start_playback

        namespace :tracks do
          get '/skip_track', to: 'skip#update', as: :skip_track
        end

        scope :playback, module: :playback do
          put '/toggle', to: 'pause_play#update', as: :toggle_playback
        end
      end
    end
  end
end

app/models/party.rb
# frozen_string_literal: true

class Party < ApplicationRecord
  belongs_to :user
  has_many :users
  has_many :party_tracks, dependent: :destroy

  validates_presence_of :user_id
  validates_presence_of :code
  validates_uniqueness_of :code

  def self.generate_party(user_id)
    user = User.find(user_id)
    Party.create(user: user, users: [user], code: generate_code)
  end

  def self.get_party_tastes(party)
    Party.select('parties.*, avg(users.acousticness) AS avg_acoust, avg(users.valence) AS avg_valence, avg(users.mode) AS avg_mode, avg(users.tempo) AS avg_tempo, avg(users.danceability) AS avg_dance, avg(users.energy) AS avg_energy')
         .joins(:users)
         .group(:id)
         .where(id: party)[0]
  end

  def new_song?
    if song_info
      return false if current_song&.spotify_id == song_info[:spotify_id]

      add_song_to_database
    end
  end

  def current_song
    party_tracks.order(:id).last
  end

  def setup_playlist
    playlist_id = playlist_service.make_playlist
    update(playlist_id: playlist_id)
  end

  def repopulate_playlist
    playlist_service.populate_playlist(playlist_id)
  end

  def update_playlist_name
    playlist_service.change_playlist_name(playlist_id, name)
  end

  private

  def self.generate_code
    RandomWord.exclude_list << /^[a-z]{6,}$/ if RandomWord.exclude_list.empty?
    RandomWord.exclude_list << /_/ if RandomWord.exclude_list.length == 1
    "#{RandomWord.adjs.first}-#{RandomWord.nouns.first}"
  end

  def song_info
    info = playlist_service.current_song
    if info
      {
        spotify_id: info[:id],
        img_url: info[:album][:images][0][:url],
        title: info[:name],
        artist: info[:artists].map { |artist| artist[:name] }.join(', ')
      }
    end
  end

  def add_song_to_database
    new_track = party_tracks.new(song_info)
    new_track.save
  end

  def playlist_service
    @playlist_service ||= PlaylistSpotifyService.new(user)
  end
end

app/controllers/host/parties_controller.rb
# frozen_string_literal: true

module Host
  # Controller for displaying party creation and show for host users
  class PartiesController < ApplicationController
    before_action :require_login
    before_action :reentry, except: %i[destroy show]

    def show
      render locals: { facade: PartyFacade.new(current_user) }
    end

    def edit
      CreatePartyJob.perform_later(current_user.id)
    end

    def update
      party = current_user.party
      if party_params[:device_id]
        party.update(party_params)
        UpdatePlaylistNameJob.perform_later(party.id)
        redirect_to host_party_path
      else
        flash[:error] = 'Please make sure you select a device'
        render :edit, locals: {
          facade: PartyFacade.new(current_user)
        }
      end
    end

    def destroy
      party = current_user.party
      party.users.update(party: nil)
      party.update(user: nil)
      party.destroy
      redirect_to root_path
    end

    private

    def party_params
      params.permit(:name, :device_id)
    end
  end
end

app/controllers/parties_controller.rb
# frozen_string_literal: true

# Controller for parties information
class PartiesController < ApplicationController
  before_action :require_login
  before_action :reentry, except: %i[show delete]
  before_action :bounce_user, only: :show

  def index; end

  def new; end

  def create
    party = Party.find_by(join_party_params)
    if party
      current_user.update(party: party)
      UpdatePlaylistJob.perform_later(party.id)
      redirect_to party_path
    else
      render :new
    end
  end

  def show
    render locals: { facade: PartyFacade.new(current_user) }
  end

  def delete
    current_user.update(party: nil)
    redirect_to root_path
  end

  private

  def bounce_user
    redirect_to root_path unless current_user.party
  end

  def join_party_params
    params[:code]&.downcase!
    params.permit(:code)
  end
end

app/views/parties/index.html.erb
<div class="root-container">
  <%= render partial: 'shared/site-logo' %>
  <div class="button-container" id='index-primary-buttons'>
    <%= button_to "Create Party", soundcheck_path, method: :get, class: 'btn btn-primary rounded', id: 'index-create-button' %>
    <%= button_to "Join Party", admissions_path, method: :get, class: 'btn btn-secondary rounded' %>
  </div>

  <div class="button-container" id="index-secondary-buttons">
    <%= button_to 'Log Out', logout_path, method: :get, class: 'btn btn-minor rounded' %>
    <div class="sub-buttons">
      <%= button_to 'Legal', legal_path, method: :get, class: 'btn sub-button rounded' %>
      <%= button_to 'About', root_path, method: :get, class: 'btn sub-button rounded' %>
    </div>
  </div>
</div>

app/views/parties/new.html.erb
<div class="room-container">
  <%= link_to image_tag('back-button.png'), root_path, method: :get, id: 'back-arrow' %>

  <section id='member-party-join'>
    <%= form_tag join_party_path, class: 'form-group' do %>
    <%= label_tag "Room Code", nil, class: 'label' %>
    <%= text_field_tag :code, nil, placeholder: 'Enter Here', class: 'input-field rounded' %>
    <%= submit_tag 'Join', class: 'btn sub-primary-button rounded' %>
    <% end %>
  </section>  
</div>

app/views/parties/show.html.erb
<div class="party-container">
  <div class="room-info-wrapper room-info-panel" id='room-name'>
    <strong><h3 class='room-info-text'>Party Name:</h3></strong><p><%= facade.name %></p>
  </div>

  <div class="room-info-wrapper room-info-panel" id='room-code'>
    <strong><h3 class='room-info-text'>Party Code:</h3></strong><p><%= facade.code %></p>
  </div>

  <div class="player-container">
    <div id="guest-album-art">
      <%= image_tag('album-loading.gif', class: 'album-artwork', id: 'album-art') %>
    </div>
    <div class="player-info-section">
      <div id="save-button" class="info-item">
        <img src="plus_template.png" alt="Plus-button" class="icon" id="save-track">
      </div>
      <div class="track-info info-item">
        <h4 id="track-title"><%= facade.name %></h4>
        <p id="track-artist">Welcome to the party.</p>
      </div>
      <div class=" info-item">
      </div>
    </div>
  </div>

  <div id="leave-party-button">
    <%= button_to 'Bail Out', leave_party_path, method: :delete, class: 'btn btn-boxed' %>
  </div>
</div>

<script type="text/javascript">
  const roomCode = "<%= facade.code %>";
</script>
<script type="text/javascript" src="/partyshow.js">
</script>